build:
  script:
    - mvn -Dmaven.repo.local=/tmp/m2/repository -Duser.home=/tmp checkstyle:check
    - mvn -Dmaven.repo.local=/tmp/m2/repository -Duser.home=/tmp test
    - mvn -Dmaven.repo.local=/tmp/m2/repository -Duser.home=/tmp cobertura:cobertura
    - "head target/site/cobertura/coverage.xml | rg --only-matching -r '$1' 'line-rate=\"([0-9.]+)\"' | awk '{ print \"Test Coverage: \" $1 * 100 \"%\" }'"
  artifacts:
    reports:
      cobertura: target/site/cobertura/coverage.xml
