build:
  script:
    - file src/main/resources/language/translation_de.properties | rg UTF-8
    - mvn -Dmaven.repo.local=/tmp/m2/repository -Duser.home=/tmp checkstyle:check jacoco:prepare-agent test jacoco:report
    - python3 /opt/cover2cover.py target/site/jacoco/jacoco.xml src/main/java > target/site/cobertura.xml
    - python3 /opt/source2filename.py target/site/cobertura.xml
    - /opt/calcCoverage.sh < target/site/cobertura.xml
  artifacts:
    reports:
      cobertura: target/site/cobertura.xml
