build:
  script:
    - mvn -Dmaven.repo.local=/tmp/m2/repository -Duser.home=/tmp checkstyle:check
    - mvn -Dmaven.repo.local=/tmp/m2/repository -Duser.home=/tmp test
    - mvn -Dmaven.repo.local=/tmp/m2/repository -Duser.home=/tmp jacoco:prepare-agent test jacoco:report
    - python3 /opt/cover2cover.py target/site/jacoco/jacoco.xml src/main/java > target/site/cobertura.xml
    - python3 /opt/source2filename.py target/site/cobertura.xml
    - /opt/calcCoverage.sh < target/site/cobertura.xml
  artifacts:
    reports:
      cobertura: target/site/cobertura.xml
